#!/usr/bin/env bash



set -e

nginx -c "$PWD/nginx.conf" &

# Apply database migrations
echo "Apply database migrations"
# python manage.py migrate

# python /app/manage.py collectstatic --noinput &
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app
wait -n